Shader "UnityEffects/DepthMap"
{
	//Generate the depth map by using _CameraDepthTexture
	Properties
	{
		_MainTex ("Texture", 2D) = "white" {}
	}
	SubShader
	{
		Tags { "RenderType"="ShadowMap" }
		LOD 100
		Pass
		{
			CGPROGRAM
			#pragma vertex vert
			#pragma fragment frag
			
			#include "UnityCG.cginc"

			struct appdata
			{
				float4 vertex : POSITION;
				float4 texPos : TEXCOORD1;
			};

			struct v2f
			{
				float4 texPos : TEXCOORD1;
				float4 vertex : SV_POSITION;
			};

			sampler2D _MainTex;
			float4 _MainTex_ST;
            uniform sampler2D _CameraDepthTexture;

			
			v2f vert (appdata v)
			{
				v2f o;
				o.vertex = mul(UNITY_MATRIX_MVP, v.vertex);
				o.texPos = o.vertex;
				o.texPos.x = o.vertex.x * 0.5f + 0.5f * o.vertex.w;//transform to x[0,w] y[0,w] space
				o.texPos.y = o.vertex.y * 0.5f  + 0.5f * o.vertex.w;
				if (_ProjectionParams.x < 0)//Uv space is platform dependent
					 o.texPos.y = o.vertex.w - o.texPos.y;//https://docs.unity3d.com/Manual/SL-PlatformDifferences.html
				return o;
			}
			
			fixed4 frag (v2f i) : SV_Target
			{
				fixed4 col = float4(0,0,0,1);
		
				//The depth of the depth map generated by unity is stored in the r channel

				float z = tex2D(_CameraDepthTexture, i.texPos.xy / i.texPos.w).r;//sample depthTexture

				return EncodeFloatRGBA(z);
			}
			ENDCG
		}
	}

	Subshader 
	{
		Tags { "RenderType"="Opaque"}
		Pass {
    		Lighting Off Fog { Mode off } 
			SetTexture [_MainTex] {
				constantColor (1,1,1,1)
				combine constant
			}
		}    
	}  
	FallBack "Diffuse"
}
